import { Box, Grid } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Editor from "../components/Editor";
import Previewer from "../components/Previewer";
import { useDocumentStore } from "../store/document";

const Home: NextPage = () => {
  const setMkd = useDocumentStore(state => state.setMarkdown);

  useEffect(() => {
    if (window?.localStorage.getItem("markdown")) {
      setMkd(window.localStorage.getItem("markdown")!);
    }
  }, [setMkd]);

  return (
    <Box>
      <Head>
        <title>MkdEdit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        templateColumns={["1fr", "repeat(2, 1fr)"]}
        minH="calc(100vh - 80px)"
        as="main"
        bg="gray.300"
        gap={0.5}
        pt={0.5}
      >
        <Editor />
        <Previewer />
      </Grid>
    </Box>
  );
};

export default Home;
